version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,lambda,dynamodb,rds,sqs,logs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - GATEWAY_LISTEN=0.0.0.0
    volumes:
      - './init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
      - .localstack:/var/lib/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
