version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  fancy:
    format: "%(asctime)s|%(levelname)s|%(module)s.%(funcName)s:%(lineno)-2s|%(message)s"
  debug:
    format: "%(asctime)s|%(levelname)s|%(pathname)s:%(funcName)s:%(lineno)-2s|%(message)s"

handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debug
    filename: events.log
    maxBytes: 1000000
    backupCount: 10
    encoding: utf8

loggers:
  boto3:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  botocore:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  RobotFramework:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  root:
    level: DEBUG
    handlers: [file_handler]