name: Run LocalStack with Docker

on:
  push:
  pull_request:

jobs:
  run-localstack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Navigate to localstack directory
      working-directory: ./localstack
      run: |
        docker-compose up -d

    - name: Wait for LocalStack to be ready
      run: sleep 20

    - name: Run tests or further commands
      working-directory: ./localstack
      run: |
        echo "LocalStack is running!"

    - name: Teardown LocalStack
      working-directory: ./localstack
      run: |
        docker-compose down